import { NextApiRequest, NextApiResponse } from 'next'
import { DiscoverRequestQuery, DiscoverResponse } from '~/services/discover'
import { paginate } from '~/utils'

const MOCKUP_DATA = [
  {
    id: 0,
    name: 'Mo Farooq',
    username: 'mofarooq32',
    avatar: 'https://i.imgur.com/9KYq7VG.png',
    is_followed: true,
    video: 'https://i.imgur.com/FTBP02Y.mp4',
    caption: 'These ducks are MEGA cute',
    likes: 10,
    comments: 2,
    shares: 666,
    timestamp: '2019-03-10T09:08:31.020Z',
    button_visible: true,
  },
  {
    id: 1,
    name: 'Tim Salowski',
    username: 'timmytam',
    avatar: 'https://i.imgur.com/rWYtZa6.png',
    is_followed: false,
    video: 'https://i.imgur.com/1A7AKoF.mp4',
    caption: 'When your fries give you attitude #getInMyBelly',
    likes: 12,
    comments: 2,
    shares: 666,
    timestamp: '2020-03-10T09:08:31.020Z',
    button_visible: true,
  },
  {
    id: 2,
    name: 'Angela Lee',
    username: 'angiecakes',
    avatar: 'https://i.imgur.com/eX3hkoc.png',
    is_followed: true,
    video: 'https://i.imgur.com/al6MLay.mp4',
    caption: 'Happiest of Birthdays my Angel',
    likes: 2,
    comments: 4,
    shares: 666,
    timestamp: '2020-04-10T09:08:31.020Z',
    button_visible: true,
  },
  {
    id: 3,
    name: 'Nina Xen',
    username: 'nina_lina',
    avatar: 'https://i.imgur.com/IigY4Hm.png',
    is_followed: false,
    video: 'https://i.imgur.com/Kzvbeup.mp4',
    caption: 'The new normal',
    likes: 10,
    comments: 2,
    shares: 666,
    timestamp: '2020-05-10T09:08:31.020Z',
    button_visible: true,
  },
  {
    id: 4,
    name: 'Lana Del Mont',
    username: 'lana_del_away',
    avatar: 'https://i.imgur.com/jONHmE5.png',
    is_followed: true,
    video: 'https://i.imgur.com/H9UX0Jm.mp4',
    caption: 'Art is for everyone',
    likes: 231,
    comments: 20,
    shares: 666,
    timestamp: '2020-09-10T09:08:31.020Z',
    button_visible: true,
  },
  {
    id: 5,
    name: 'Mo Farooq',
    username: 'mofarooq32',
    avatar: 'https://i.imgur.com/HLHBnl9.png',
    is_followed: true,
    video: 'https://i.imgur.com/wCadaAi.mp4',
    caption: 'These ducks are MEGA cute',
    likes: 10,
    comments: 2,
    shares: 666,
    timestamp: '2019-03-10T09:08:31.020Z',
    button_visible: true,
  },
  {
    id: 6,
    name: 'Tim Salowski',
    username: 'timmytam',
    avatar: 'https://i.imgur.com/HmrMAcT.png',
    is_followed: false,
    video: 'https://i.imgur.com/65Z9Dua.mp4',
    caption: 'When your fries give you attitude #getInMyBelly',
    likes: 12,
    comments: 2,
    shares: 666,
    timestamp: '2020-03-10T09:08:31.020Z',
    button_visible: true,
  },
  {
    id: 7,
    name: 'Kim',
    username: 'kimtheproduct',
    avatar: 'https://i.imgur.com/AbE3RPR.png',
    is_followed: true,
    video: 'https://i.imgur.com/al6MLay.mp4',
    caption: 'Happiest of Birthdays my Angel',
    likes: 2,
    comments: 4,
    shares: 666,
    timestamp: '2020-04-10T09:08:31.020Z',
    button_visible: true,
  },
  {
    id: 8,
    name: 'Nina Xen',
    username: 'nina_lina',
    avatar: 'https://i.imgur.com/IigY4Hm.png',
    is_followed: false,
    video: 'https://i.imgur.com/VyZ34Go.mp4',
    caption: 'The new normal',
    likes: 10,
    comments: 2,
    shares: 666,
    timestamp: '2020-05-10T09:08:31.020Z',
    button_visible: true,
  },
  {
    id: 9,
    name: 'Lana Del Mont',
    username: 'lana_del_away',
    avatar: 'https://i.imgur.com/jONHmE5.png',
    is_followed: true,
    video: 'https://i.imgur.com/7DMCgvT.mp4',
    caption: 'Art is for everyone',
    likes: 231,
    comments: 20,
    shares: 666,
    timestamp: '2020-09-10T09:08:31.020Z',
    button_visible: true,
  },
  {
    id: 10,
    name: 'Mo Farooq',
    username: 'mofarooq32',
    avatar: 'https://i.imgur.com/9KYq7VG.png',
    is_followed: true,
    video: 'https://i.imgur.com/FTBP02Y.mp4',
    caption: 'These ducks are MEGA cute',
    likes: 10,
    comments: 2,
    shares: 666,
    timestamp: '2019-03-10T09:08:31.020Z',
    button_visible: true,
  },
  {
    id: 11,
    name: 'Tim Salowski',
    username: 'timmytam',
    avatar: 'https://i.imgur.com/rWYtZa6.png',
    is_followed: false,
    video: 'https://i.imgur.com/1A7AKoF.mp4',
    caption: 'When your fries give you attitude #getInMyBelly',
    likes: 12,
    comments: 2,
    shares: 666,
    timestamp: '2020-03-10T09:08:31.020Z',
    button_visible: true,
  },
  {
    id: 12,
    name: 'Angela Lee',
    username: 'angiecakes',
    avatar: 'https://i.imgur.com/eX3hkoc.png',
    is_followed: true,
    video: 'https://i.imgur.com/al6MLay.mp4',
    caption: 'Happiest of Birthdays my Angel',
    likes: 2,
    comments: 4,
    shares: 666,
    timestamp: '2020-04-10T09:08:31.020Z',
    button_visible: true,
  },
  {
    id: 13,
    name: 'Nina Xen',
    username: 'nina_lina',
    avatar: 'https://i.imgur.com/IigY4Hm.png',
    is_followed: false,
    video: 'https://i.imgur.com/Kzvbeup.mp4',
    caption: 'The new normal',
    likes: 10,
    comments: 2,
    shares: 666,
    timestamp: '2020-05-10T09:08:31.020Z',
    button_visible: true,
  },
  {
    id: 14,
    name: 'Lana Del Mont',
    username: 'lana_del_away',
    avatar: 'https://i.imgur.com/jONHmE5.png',
    is_followed: true,
    video: 'https://i.imgur.com/H9UX0Jm.mp4',
    caption: 'Art is for everyone',
    likes: 231,
    comments: 20,
    shares: 666,
    timestamp: '2020-09-10T09:08:31.020Z',
    button_visible: true,
  },
]

const handler = (req: NextApiRequest, res: NextApiResponse<DiscoverResponse>) => {
  if (req.method === 'GET') {
    const { page = '1', offset = '5' } = req.query as unknown as DiscoverRequestQuery

    const data = paginate(MOCKUP_DATA, parseInt(page as string), parseInt(offset as string))

    return res.status(201).send({ message: 'Success', data: data })
  }

  return res.status(404).send({ message: 'Invalid request' })
}

export default handler
